version: '3.3'
services:

  noticias_db:
    image: 'mariadb:10.5.9'
    container_name: noticias_db
    volumes:
      - './mysql:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_DATABASE: 'noticias_dsa'
      MYSQL_ROOT_PASSWORD: 'root'

  noticias_web:
    image: wordpress:php8.0
    container_name: noticias_web
    ports:
      - '80:80'
      - '443:443'
    links:
      - noticias_db
    volumes:
      - ./app:/var/www/html
      - ./config/certs:/var/www/certs:ro
      - ./config/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf:ro
      - ./config/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
      - ./extras/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html
      WP_DB_NAME: 'noticias_dsa'
      WP_DB_USER: 'root'
      WP_DB_PASSWORD: 'root'
      WP_DB_HOST: 'noticias_db'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: noticias_phpmyadmin
    environment:
      PMA_HOST: noticias_db
    ports:
      - 8080:80
    depends_on:
      - noticias_db
    restart: always