<?php 

class TempoReal_FieldsACF {
	public static function acf_fields(){
		acf_add_local_field_group(array (
			'key' => 'group_582996a3e9bdb',
			'title' => 'Design',
			'fields' => array (
				array (
					'key' => 'field_582996a8bf509',
					'label' => 'Imagem de fundo',
					'name' => 'bg_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '571',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_582996febf50c',
					'label' => 'Cor de fundo',
					'name' => 'bg_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array (
					'key' => 'field_582996ebbf50b',
					'label' => 'Cor para texto',
					'name' => 'text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array (
					'key' => 'field_582996dabf50a',
					'label' => 'Imagem de fundo do rodapé',
					'name' => 'bg_image_footer',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'page_template',
						'operator' => '==',
						'value' => 'page-tempo-real.php',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'side',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => 1,
			'description' => '',
			'modified' => 1493059415,
		));

		acf_add_local_field_group(array (
			'key' => 'group_57d8aee378355',
			'title' => 'Tempo Real',
			'fields' => array (
				array (
					'key' => 'field_57d956eb2aeb2',
					'label' => 'Status',
					'name' => 'status',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'horizontal',
					'choices' => array (
						'waiting' => 'Não começou',
						'live' => 'Acontecendo',
						'finished' => 'Finalizado',
					),
					'default_value' => 'waiting',
					'other_choice' => 0,
					'save_other_choice' => 0,
					'allow_null' => 0,
					'return_format' => 'value',
				),
				array (
					'key' => 'field_5829bbd8f7f9e',
					'label' => 'Transmissão',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_57d95f318e2b6',
					'label' => 'Transmissão',
					'name' => 'has_transmition',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 0,
					'message' => '',
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_590c8d5a9a324',
					'label' => 'JSON URL',
					'name' => 'json_url',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_57d8af1c9578b',
					'label' => 'Embed',
					'name' => 'embed_live',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57d95f318e2b6',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'tabs' => 'text',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'default_value' => '',
					'delay' => 0,
				),
				array (
					'key' => 'field_5829bc91f7fa3',
					'label' => 'Outros vídeos',
					'name' => 'broadcast_archive',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Adicionar vídeo',
					'collapsed' => 'field_5829bcb2f7fa4',
					'sub_fields' => array (
						array (
							'key' => 'field_5829bcb2f7fa4',
							'label' => 'Título',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5829bcb8f7fa5',
							'label' => 'Imagem',
							'name' => 'thumbnail',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '740',
							'min_height' => '475',
							'min_size' => '',
							'min_width' => '740',
							'min_height' => '475',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_5829bd35f7fa6',
							'label' => 'Video URL',
							'name' => 'link',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
					),
				),
				array (
					'key' => 'field_5829bbe3f7f9f',
					'label' => 'Minuto a minuto',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_590c8d5a9a893',
					'label' => 'Titulo 24Liveblog',
					'name' => '24liveblog_titulo',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_57d8af419578c',
					'label' => 'Minuto a minuto',
					'name' => '24liveblog_ID',
					'type' => 'text',
					'instructions' => '<strong>ID do evento</strong> criado 24Liveblog. <a href="https://cloud.24liveblog.com/event/create" target="_blank">Crie um aqui</a>',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5829bc0af7fa0',
					'label' => 'Resumos',
					'name' => 'resumo',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Adicionar resumo',
					'collapsed' => 'field_5829bc62f7fa1',
					'sub_fields' => array (
						array (
							'key' => 'field_582a041b6f36f',
							'label' => 'Taxonomia',
							'name' => 'tax',
							'type' => 'text',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5829bc62f7fa1',
							'label' => 'Título',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5829bc68f7fa2',
							'label' => 'Conteúdo',
							'name' => 'content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'tabs' => 'visual',
							'toolbar' => 'basic',
							'media_upload' => 1,
							'default_value' => '',
							'delay' => 0,
						),
					),
				),
				array (
					'key' => 'field_590c8d5a9a741',
					'label' => 'Titulo Filtros',
					'name' => 'filters_titulo',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_582b86b597a3a',
					'label' => 'Filtros',
					'name' => 'filters',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'min' => 0,
					'max' => 0,
					'layout' => 'row',
					'button_label' => 'Adicionar Texto',
					'collapsed' => '',
					'sub_fields' => array (
						array (
							'key' => 'field_582b86f797a3b',
							'label' => 'Texto',
							'name' => 'text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'page_template',
						'operator' => '==',
						'value' => 'page-tempo-real.php',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => 1,
			'description' => '',
			'modified' => 1493059394,
		));
	}
}

add_action( 'after_setup_theme', array('TempoReal_FieldsACF', 'acf_fields'), 0 ); 